version: '3.8'

services:
  david-web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - david-db
    environment:
      - DB_HOST=david-db
      - DB_NAME=221010123_shareride_db
      - DB_USER=root
      - DB_PASS=password

  david-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 221010123_shareride_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  david-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: david-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - david-db

volumes:
  db_data: